apiVersion: v1
kind: Service
metadata:
  name: insurance-quote-api-service
spec:
  selector:
    app: insurance-quote-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP